# Change these first
owner: Rashnan # Your GitHub organization or username, where this repository lives
repo: mnu-uptime # The name of this repository

sites:
  - name: MNU
    url: https://mnu.edu.mv
  - name: Moodle - Latest Term
    url: https://moodle.mnu.edu.mv
  - name: SelfService
    url: https://selfservice.mnu.edu.mv/Default
  - name: Exam Portal
    url: https://exam.mnu.edu.mv
  - name: MyMNU Portal - Existing Students Online Forms
    url: https://my.mnu.edu.mv
  - name: Courses
    url: https://courses.mnu.edu.mv
  - name: Application Portal - New Students Registration
    url: https://portal.mnu.edu.mv
  - name: Helpdesk
    url: https://helpdesk.mnu.edu.mv
  - name: Library OPAC
    url: http://202.1.196.72:8080/sahara/opac/search/reset.do?SAMLResponse=&clientAlias=&time=&digest=&corporationAlias=mche
  - name: Saruna
    url: https://saruna.mnu.edu.mv
  - name: Marathon
    url: https://marathon.mnu.edu.mv
  # - name: Moodle (24t2)
  #   url: https://moodle24t2.mnu.edu.mv
  # - name: Moodle (24t1)
  #   url: https://moodle24t1.mnu.edu.mv
  # - name: Moodle (23t2)
  #   url: https://moodle23t2.mnu.edu.mv
  # - name: Moodle (23t1)
  #   url: https://moodle23t1.mnu.edu.mv

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /mnu-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: MNU Uptime Tracker
  introTitle: Tracking the uptime of The Maldives National University (MNU) website.
  introMessage: This status page tracks real-time data of all subdomains under MNU. For any incidents, check the Github issues to see more information. Made by [Rashnan](https://github.com/Rashnan)
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
